Jdp220901 3
pplutap/project-jdp-2209-01 pull request #11
Opened 2022-08-19 19:20 UTC by ania4134

2022-08-20 18:44 UTC, pplutap requested changes

2022-08-20 18:44 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +public class Cart {
Czy klasa jest potrzebna? Encje będziemy robić po uzgodnieniu schematu bazy danych

2022-08-21 13:01 UTC, ania4134 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +public class Cart {
Racja, juz ja usuwam

2022-08-22 07:28 UTC, pplutap approved these changes

2022-08-22 09:48 UTC, merged