Cart class added
pplutap/project-jdp-2209-01 pull request #16
Opened 2022-08-27 20:22 UTC by ania4134

Sporo tekstu jest zakomentowanego z powodu braku klas User i ProductRequest

2022-08-27 21:09 UTC, pplutap requested changes

2022-08-27 21:09 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private long id;
Lepiej byłoby gdyby zmienna była typu obiektowego

2022-08-27 21:19 UTC, plecicki reviewed
Brakuje repozytorium o którym jest mowa w opisie zadania w Jira i do tego jeszcze proponuję zmienić typ id na typ obiektowy z long na Long tam gdzie Paweł dodał komentarz, bo inaczej będzie problem ze stworzeniem repozytorium

2022-08-28 07:27 UTC, wmodlinski approved these changes

2022-08-28 16:23 UTC, ania4134 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private long id;
Racja, juz zmienione

2022-08-28 16:23 UTC, ania4134 commented
> Brakuje repozytorium o którym jest mowa w opisie zadania w Jira i do tego jeszcze proponuję zmienić typ id na typ obiektowy z long na Long tam gdzie Paweł dodał komentarz, bo inaczej będzie problem ze stworzeniem repozytorium

2022-08-29 07:46 UTC, plecicki approved these changes

2022-08-29 07:52 UTC, kamiljanusztc approved these changes

2022-08-29 07:53 UTC, wmodlinski approved these changes

2022-08-29 13:07 UTC, pplutap approved these changes

2022-08-30 15:26 UTC, merged