Uncommenting the text
pplutap/project-jdp-2209-01 pull request #23
Opened 2022-09-02 22:06 UTC by ania4134

2022-09-02 22:14 UTC, ania4134 commented
po dodaniu PR zauwazylam ze CircleCI wyrzuca blad. W Intelii gradlew buduje sie pomyslnie

2022-09-04 18:12 UTC, pplutap requested changes
W trakcie uruchamiania projektu pojawia się błąd:
```
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "alter table products add constraint FKi64j64p0ru6scf2ifqisn4mu7 foreign key (group) references groups (group_id)" via JDBC Statement 
```

2022-09-05 14:28 UTC, ania4134 commented
> W trakcie uruchamiania projektu pojawia się błąd:
> 
> ```
> org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "alter table products add constraint FKi64j64p0ru6scf2ifqisn4mu7 foreign key (group) references groups (group_id)" via JDBC Statement 
> ```

Zmieniłam nazwę encji Group oraz biblioteki i pozbyłam się błędu

2022-09-05 14:32 UTC, pplutap requested changes

2022-09-05 14:32 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private RequestProduct requestProduct;
Czy to na pewno relacja 1:1?

2022-09-05 14:32 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private RequestProduct requestProduct;
Czy to na pewno relacja 1:1?

2022-09-05 15:23 UTC, ania4134 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private RequestProduct requestProduct;
taka sama sytuacja jak wyzej

2022-09-05 17:01 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private RequestProduct requestProduct;
Masz rację :) Sugerowałem się tym, że miedzy Product a ProductRequest jest relacja 1:1. Jest tam 1:N

2022-09-05 17:02 UTC, pplutap approved these changes

2022-09-05 17:18 UTC, kamiljanusztc approved these changes

2022-09-06 07:22 UTC, Dragdas approved these changes

2022-09-06 08:29 UTC, KarolZmarz approved these changes

2022-09-06 08:29 UTC, merged