Jdp220901 20
pplutap/project-jdp-2209-01 pull request #32
Opened 2022-09-09 22:01 UTC by ania4134

User tests

2022-09-10 14:45 UTC, pplutap requested changes

2022-09-10 14:45 UTC, pplutap commented on src/test/java/com/kodilla/ecommercee/entities/UserTestSuite.java
> +        Assert.assertEquals(true, isExist);
Zastosuj proszę `assertTrue`

2022-09-10 14:45 UTC, pplutap commented on src/test/java/com/kodilla/ecommercee/entities/UserTestSuite.java
> +        Assert.assertEquals(false, isExist);
Zastosuj proszę `assertFalse`

2022-09-10 20:55 UTC, ania4134 commented on src/test/java/com/kodilla/ecommercee/entities/UserTestSuite.java
> +        Assert.assertEquals(true, isExist);
zrobione

2022-09-10 20:55 UTC, ania4134 commented on src/test/java/com/kodilla/ecommercee/entities/UserTestSuite.java
> +        Assert.assertEquals(false, isExist);
zrobione

2022-09-11 12:48 UTC, pplutap approved these changes

2022-09-11 14:40 UTC, mwojtas89 approved these changes

2022-09-11 16:43 UTC, kamiljanusztc approved these changes

2022-09-11 18:22 UTC, merged